version: "3.9"

services:
  backend:
    build: ./backend
    container_name: boxoffice-backend
    image: boxoffice-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: boxoffice-frontend
    image: boxoffice-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000"
    restart: unless-stopped

